FROM php:8.1

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip

ARG projectname=Loris-MRI
RUN useradd -ms /bin/bash lorisadmin \
    && mkdir -p /data/${projectname} \
    && mkdir -p /opt/${projectname}/bin/mri \
WORKDIR /opt/${projectname}/bin/mri

# Update packages and install necessary tools and libraries
RUN apt-get update \
    && apt-get install -y \
        python3 \
        wget \
        imagemagick \
        python3-dev \
        python3-pip \
        default-libmysqlclient-dev \
        virtualenv \
    && rm -rf /var/lib/apt/lists/*


########################
# Install MINC Toolkit #
########################

# Install MINC Toolkit dependencies
RUN apt-get install -y libc6 libstdc++6 imagemagick perl

# Download the MINC Toolkit package
RUN wget -P /tmp http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.9.18-20200813-Debian_10-x86_64.deb

# Install the MINC Toolkit package
RUN dpkg -i /tmp/minc-toolkit-1.9.18-20200813-Debian_10-x86_64.deb

# Run the MINC Toolkit configuration script 
RUN . /opt/minc/1.9.18/minc-toolkit-config.sh

RUN wget -P /tmp https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-testsuite-0.1.3-20131212.deb
RUN wget -P /tmp https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/bic-mni-models-0.1.1-20120421.deb
RUN wget -P /tmp https://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/beast-library-1.1.0-20121212.deb
RUN dpkg -i /tmp/bic-mni-models-0.1.1-20120421.deb
RUN dpkg -i /tmp/bic-mni-models-0.1.1-20120421.deb
RUN dpkg -i /tmp/beast-library-1.1.0-20121212.deb


