FROM php:8.1

RUN cat /etc/os-release

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip

# todo install loris-mri here

# Update the package list and install build-essential, checkinstall, and cmake
RUN apt-get update && \
    apt-get install -y build-essential checkinstall cmake

# Install Perl and CPAN
RUN apt-get install -y perl && \
    apt-get install -y libterm-readline-gnu-perl && \
    apt-get install -y perl-doc && \
    apt-get install -y libssl-dev && \
    apt-get install -y liblwp-protocol-https-perl && \
    cpan CPAN

# Update the package list and install required packages

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    libmariadb-dev-compat \
    libmariadb-dev \
    virtualenv
