#!/usr/bin/perl -w
use strict;


#####Get config setting#######################################################
# checking for profile settings
if(-f "$ENV{HOME}/.neurodb/prod") {
    { package Settings; do "$ENV{HOME}/.neurodb/prod" }
} ##Possibly the script can exit if the prod doesn't exist
#######################################################################################
# define project space
my ($debug, $verbose) = (0,0);
my ($stdoutbase, $stderrbase) = ("$Settings::data_dir/batch_output/tarstdout.log", "$Settings::data_dir/batch_output/tarstderr.log");
my $stdout = '';
my $stderr = '';
while($_ = $ARGV[0], /^-/) {
    shift;
    last if /^--$/; ## -- ends argument processing
    if (/^-D/) { $debug++ } ## debug level
    if (/^-v/) { $verbose++ } ## verbosity
}

## read input from STDIN, store into array @inputs (`find ....... | this_script`)
my @inputs = ();
my @submitted = ();
while(<STDIN>)
{
    chomp;
    push @inputs, $_;
}
close STDIN;

my $counter = 0;

## foreach series, batch magic
foreach my $input (@inputs)
{
    $counter++;
    $stdout = $stdoutbase.$counter;
    $stderr = $stderrbase.$counter;

    #$stdout = '/dev/null';
    #$stderr = '/dev/null';

    ## this is where the subprocesses are created...  should basically run processor script with study directory as argument.
    ## processor will do all the real magic

    $input =~ s/\t/ /;
    my $command = "copy_and_process_tarchive $input $Settings::prefix $Settings::mail_user $Setting::tarchiveLibraryDir";
    ##if qsub is enabled use it
    if ($Settings::is_qsub) {
	     open QSUB, "| qsub -V -e $stderr -o $stdout -N process_tarchive_${counter}";
    	 print QSUB $command;
    	 close QSUB;
    }
    ##if qsub is not enabled
    else {
         system($command);
    }

     push @submitted, $input;
}
open MAIL, "|mail $Settings::mail_user";
print MAIL "Subject: BATCH_UPLOADS_TARCHIVE: ".scalar(@submitted)." studies submitted.\n";
print MAIL join("\n", @submitted)."\n";
close MAIL;

## exit 0 for find to consider this -cmd true (in case we ever run it that way...)
exit(0);
