#!/bin/bash

site=$1
tarchive=$2

if [ -z "$site" -o -z "$tarchive" ]
then
echo "Usage: $0 <site> <tarchive>"
exit 1
fi

tempdir=$TMPDIR/load_tarchive_db.$$
mkdir -p $tempdir

# copy the tarchive from the study workstation to here
if cp /data/incoming/${site}IBIS/incoming/$tarchive $tempdir/

# if the copy succeeded
then

# process the tarchive
/data/ibis/bin/mri/uploadNeuroDB/tarchiveLoader -globLocation -profile prod $tempdir/`basename $tarchive`

# if the copy failed
else

# email samir
echo "Subject: SCP TARCHIVE FAILURE\nFailed to scp ${site} ${tarchive}"  | mail samir@bic.mni.mcgill.ca

fi

rm -fr $tempdir
exit 0
