#!/bin/bash



site=$1
tarchive=$2
proj=$3
mail_user=$4
if [ -z "$site" -o -z "$tarchive" ]
then
echo "Usage: $0 <site> <tarchive>"
exit 1
fi


tempdir=$TMPDIR/load_tarchive_db.$$
mkdir -p $tempdir

# copy the tarchive from the study workstation to here
if cp /data/incoming/${site}$proj/incoming/$tarchive $tempdir/

# if the copy succeeded
then

# process the tarchive
uploadNeuroDB/tarchiveLoader -globLocation -profile prod $tempdir/`basename $tarchive`

# if the copy failed
else

# email the user
echo "Subject: SCP TARCHIVE FAILURE\nFailed to scp ${site} ${tarchive}"  | mail $mail_user

fi

rm -fr $tempdir
exit 0
