FROM php:8.1

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip

# Update the package list and install build-essential, checkinstall, and cmake
RUN apt-get update && \
    apt-get install -y build-essential checkinstall cmake

# Install Perl and CPAN
RUN apt-get install -y perl && \
    apt-get install -y libterm-readline-gnu-perl && \
    apt-get install -y perl-doc && \
    apt-get install -y libssl-dev && \
    apt-get install -y liblwp-protocol-https-perl && \
    cpan CPAN

# Reload CPAN to update metadata
RUN cpan reload cpan

# Now you can install CPAN modules or use CPAN commands


# Continue with your Dockerfile steps
# Create directories and list files
RUN mkdir -p /data/Loris-mri && \
    mkdir -p /opt/Loris-mri/bin/mri && \
    pwd && \
    echo "====" && \
    ls -l

# Copy files from the current directory to the destination
COPY . /opt/Loris-mri/bin/mri


# Update the package list and install required packages
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    libmysqlclient-dev \
    virtualenv

RUN cd /opt/Loris-mri/bin/mri/install/ && \
    bash ./imaging_install.sh

