# NOTES:
# - Module::Pluggable is required by other modules. Installation fails for v6.1
#   (at the time of this writing)
# - DBD::mysql v5+ is no longer compatible with MariaDB
requires 'Module::Pluggable', '== 5.2';
requires 'DBD::mysql', '== 4.052';
requires 'Math::Round';
requires 'DateTime';
requires 'Date::Parse';
requires 'DBI';
requires 'Getopt::Tabular';
requires 'Time::JulianDay';
requires 'Path::Class';
requires 'Archive::Extract';
requires 'Archive::Zip';
requires 'Pod::Perldoc';
requires 'Pod::Markdown';
requires 'Pod::Usage';
requires 'JSON';
requires 'Moose';
requires 'MooseX::Privacy';
requires 'TryCatch';
requires 'Throwable';
requires 'File::Type';
requires 'String::ShellQuote';
