name: Set up Python
input:
inputs:
  python-version:
    required: true

runs:
  using: composite

  steps:
  - name: Set up the Python environment
    uses: actions/setup-python@v5
    with:
      python-version: ${{ matrix.python-version }}
      cache: 'pip'

  - name: Install Python dependencies
    run: pip install -r install/requirements/requirements.txt
    shell: bash

  - name: Set up environment variables
    run: echo PYTHONPATH=$PYTHONPATH:/`pwd`/python:/`pwd`/python/react-series-data-viewer >> $GITHUB_ENV
    shell: bash
