name: Set up Python
input:
inputs:
  python-version:
    required: true

runs:
  using: composite

  steps:
  - name: Set up the Python environment
    uses: actions/setup-python@v5
    with:
      python-version: ${{ matrix.python-version }}
      cache: 'pip'

  - name: Install Python dependencies
    run: pip install .[dev]
    shell: bash
