# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hunk.proto\"R\n\nFloatChunk\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x14\n\x0c\x64ownsampling\x18\x02 \x01(\x03\x12\x0e\n\x06\x63utoff\x18\x03 \x01(\x03\x12\x0f\n\x07samples\x18\x04 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chunk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOATCHUNK._serialized_start=15
  _FLOATCHUNK._serialized_end=97
# @@protoc_insertion_point(module_scope)
