# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol-buffers/chunk.proto

"""
Script to chunk EEG data in smaller bits for the React viewer of LORIS.

This script was extracted on November 20th, 2018 from the master branch of the
following Github repository https://github.com/ArminTaheri/react-series-data-viewer.

Author: Armin Taheri; armin.taheri@mcgill.ca
"""

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol-buffers/chunk.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cprotocol-buffers/chunk.proto\"R\n\nFloatChunk\x12\r\n\x05index\x18\x01 \x01(\x03\x12\x14\n\x0c\x64ownsampling\x18\x02 \x01(\x03\x12\x0e\n\x06\x63utoff\x18\x03 \x01(\x03\x12\x0f\n\x07samples\x18\x04 \x03(\x02\x62\x06proto3')
)




_FLOATCHUNK = _descriptor.Descriptor(
  name='FloatChunk',
  full_name='FloatChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='FloatChunk.index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='downsampling', full_name='FloatChunk.downsampling', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cutoff', full_name='FloatChunk.cutoff', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='FloatChunk.samples', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['FloatChunk'] = _FLOATCHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FloatChunk = _reflection.GeneratedProtocolMessageType('FloatChunk', (_message.Message,), dict(
  DESCRIPTOR = _FLOATCHUNK,
  __module__ = 'protocol_buffers.chunk_pb2'
  # @@protoc_insertion_point(class_scope:FloatChunk)
  ))
_sym_db.RegisterMessage(FloatChunk)


# @@protoc_insertion_point(module_scope)
