# This workflow runs flake8 with reviewdog. The documentation can be found below:
# https://github.com/marketplace/actions/run-flake8-with-reviewdog
# Flake8 is a Python linter that analyzes code and checks for programming and stylistic errors
name: Flake8 Linter

# This workflow acts only on pull requests
on: pull_request

jobs:

  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Check out source repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: pip install -r python/requirements.txt

  ruff:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run Ruff
        run: ruff check

  pyright-strict:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Run Pyright
      run: pyright

  pyright-loose:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Run Pyright
      run: |
        cd test
        pyright
