name: Python checks

on:
  - push
  - pull_request

jobs:

  ruff:
    name: "Ruff"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up the Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install -r python/requirements.txt

    - name: Run Ruff
      run: ruff check

  pyright-strict:
    name: "Pyright strict"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up the Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install -r python/requirements.txt

    - name: Run Pyright
      run: pyright

  pyrigh-global:
    name: "Pyright global"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up the Python environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install -r python/requirements.txt

    - name: Run Pyright
      run: |
        cd test
        pyright
