name: Static tests

on:
  pull_request:
  push:
    branches:
    - 'main'
    - '*-release'
  schedule:
    - cron: '30 0 * * *'

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up Python
      uses: ./.github/actions/setup-python
    - name: Run Ruff
      run: ruff check --output-format=github

  pyright-strict:
    name: Pyright strict
    runs-on: ubuntu-latest

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Run Pyright
      run: |
        set -o pipefail
        pyright --outputjson | test/pyright_to_github.sh

  pyrigh-global:
    name: Pyright global
    runs-on: ubuntu-latest

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Run Pyright
      run: |
        set -o pipefail
        pyright --project test --outputjson | test/pyright_to_github.sh

  pytest:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out LORIS-MRI
      uses: actions/checkout@v4

    - name: Set up Python
      uses: ./.github/actions/setup-python

    - name: Run Pytest
      run: pytest python/tests/unit
